{
  "classifiers": [
    "development status :: 5 - production/stable",
    "environment :: web environment",
    "framework :: zope :: 3",
    "intended audience :: developers",
    "license :: osi approved :: zope public license",
    "natural language :: english",
    "operating system :: os independent",
    "programming language :: python",
    "programming language :: python :: 3",
    "programming language :: python :: 3.10",
    "programming language :: python :: 3.11",
    "programming language :: python :: 3.7",
    "programming language :: python :: 3.8",
    "programming language :: python :: 3.9",
    "programming language :: python :: implementation :: cpython",
    "programming language :: python :: implementation :: pypy",
    "topic :: internet :: www/http"
  ],
  "description": "=================\n zope.exceptions\n=================\n\n.. image:: https://img.shields.io/pypi/v/zope.exceptions.svg\n        :target: https://pypi.python.org/pypi/zope.exceptions/\n        :alt: latest release\n\n.. image:: https://img.shields.io/pypi/pyversions/zope.exceptions.svg\n        :target: https://pypi.org/project/zope.exceptions/\n        :alt: supported python versions\n\n.. image:: https://github.com/zopefoundation/zope.exceptions/actions/workflows/tests.yml/badge.svg\n        :target: https://github.com/zopefoundation/zope.exceptions/actions/workflows/tests.yml\n\n.. image:: https://coveralls.io/repos/github/zopefoundation/zope.exceptions/badge.svg?branch=master\n        :target: https://coveralls.io/github/zopefoundation/zope.exceptions?branch=master\n\n.. image:: https://readthedocs.org/projects/zopeexceptions/badge/?version=latest\n        :target: https://zopeexceptions.readthedocs.io/en/latest/\n        :alt: documentation status\n\nthis package contains exception exceptions and implementations which are so\ngeneral purpose that they don't belong in zope application-specific packages.\n\nplease see https://zopeexceptions.readthedocs.io/ for the documentation.\n\n\n===========================\n zope.exceptions changelog\n===========================\n\n5.0.1 (2023-07-11)\n==================\n\n- fix issue introduced in the last release which is breaking\n  ``htmlexceptionformatter`` when using non-str ``__traceback_info__``.\n\n\n5.0 (2023-06-29)\n================\n\n- drop support for python 2.7, 3.5, 3.6.\n\n\n4.6 (2022-11-10)\n================\n\n- catch exceptions in ``formatexceptiononly``.\n  getting an exception when reporting about a different exception is not helpful.\n  on python 3.11 this is needed for some httperrors.\n\n- add official support for python 3.11.\n\n\n4.5 (2022-02-11)\n================\n\n- add official support for python 3.9 and 3.10.\n\n- undo dropping support for python 3.5.\n\n- drop support for running the tests using ``python setup.py test``.\n\n\n4.4 (2020-07-16)\n================\n\n- add support for python 3.8 and preliminary support for 3.9b4.\n\n- drop support for python 3.4 and 3.5.\n\n\n4.3 (2018-10-04)\n================\n\n- add support for python 3.7.\n\n\n4.2.0 (2017-09-12)\n==================\n\n- add support for python 3.6.\n\n- drop support for python 3.3.\n\n- fix handling of unicode supplemental traceback information on\n  python 2. now such values are always encoded to utf-8; previously\n  the results were undefined and depended on system encodings and the\n  values themselves. see `issue 1 <https://github.com/zopefoundation/zope.exceptions/issues/1>`_.\n\n4.1.0 (2017-04-12)\n==================\n\n- drop support for python 2.6 and 3.2.\n\n- make ``exceptionformatter.extract_stack`` signature comply with\n  ``traceback.extract_stack``\n\n- add support for python 3.5.\n\n4.0.8 (2015-08-13)\n==================\n\n- fixes around ``textexceptionformatter`` ``limit``: ``formatexception``\n  and ``extractstack`` was cutting the traceback at the bottom,\n  at the most interesting point. now it will cut from the middle.\n  some text about the missing entries will be inserted.\n\n- maybe fix for ``extractstack``, it did not detect recursions in the frames.\n\n4.0.7 (2014-03-19)\n==================\n\n- added explicit support for python 3.4.\n\n- updated ``boostrap.py`` to version 2.2.\n\n\n4.0.6 (2013-02-28)\n==================\n\n- make sure that ``setup.py`` finds all tests. now tox runs them all as well.\n\n- fix failing test under python 3.\n\n- made buildout work under python 3 and buildout 2.\n\n\n4.0.5 (2012-12-31)\n==================\n\n- fleshed out pypi trove classifiers.\n\n- fixed a test failure under python 2.6.\n\n\n4.0.4 (2012-12-13)\n==================\n\n- release with a fixed manifest.in (without ``docs/``)\n\n\n4.0.3 (2012-12-10)\n==================\n\n- fixed format_exception(..., as_html=true) not to html-escape the '<br />'\n  it adds to the exception value.\n\n\n4.0.2 (2012-11-21)\n==================\n\n- test python 3.3 support under tox.\n\n\n4.0.1 (2012-08-20)\n==================\n\n- fixed optional dependency code for `'zope.security`` to work under python 3.3.\n\n\n4.0.0.1 (2012-05-16)\n====================\n\n- fixed rendering of package docs on pypi.\n\n\n4.0.0 (2012-05-16)\n==================\n\n- automated build of sphinx html docs and running doctest snippets via tox.\n\n- added sphinx documentation.\n\n- added support for continuous integration using ``tox`` and ``jenkins``.\n\n- removed use of '2to3' and associated fixers when installing under py3k.\n  the code is now in a \"compatible subset\" which supports python 2.6, 2.7,\n  and 3.2, including pypy 1.8 (the version compatible with the 2.7 language\n  spec).\n\n- 100% unit test coverage.\n\n- dropped explicit support for python 2.4 / 2.5 / 3.1.\n\n- added 'setup.py dev' alias (runs ``setup.py develop`` plus installs\n  ``nose`` and ``coverage``).\n\n- added 'setup.py docs' alias (installs ``sphinx`` and dependencies).\n\n\n3.7.1 (2012-03-28)\n==================\n\n- fix: missed to reverse extractstack entries\n\n\n3.7.0 (2012-03-28)\n==================\n\n- added textexceptionformatter.extractstack and extract_stack\n\n\n3.6.2 (2012-03-28)\n==================\n\n- fallback to traceback.format_tb when the formatter is called recursively.\n  i.e. don't let errors in the formatter pass silently.\n\n- fix deprecated unittest functions: ``assert_`` and ``assertequals``.\n\n3.6.1 (2010-07-06)\n==================\n\n- fixed tests to work under python 2.7.\n\n- pep8 cleanup and removed obsolete build infrastructure files.\n\n\n3.6.0 (2010-05-02)\n==================\n\n- added support to bootstrap on jython.\n\n- added python 3 support.\n\n- the dependency on zope.testing seemed spurious, possibly a rest of a real\n  dependency that is gone now. i removed it.\n\n\n3.5.2 (2008-04-30)\n==================\n\n- updated changes.txt.\n\n\n3.5.1 (2008-04-28)\n==================\n\n- reverted changes in 3.5.0.\n\n\n3.5.0\n=====\n\n- added the capability for exceptions to be formatted line-by-line.\n  unfortunately, also introduced a bug cause each line of the exception to be\n  its own log message.\n\n\n3.4.0 (2007-10-02)\n==================\n\n- updated package meta-data.\n\n\n3.4.0b2 (2007-08-14)\n====================\n\n- removed superfluous dependency on ``zope.deprecation``.\n\n\n3.4.0b1 (2007-07-09)\n====================\n\n- corresponds to the version of the ``zope.exceptions`` package shipped as\n  part of the zope 3.4.0b1 release.\n\n\n3.2.0 (2006-01-05)\n==================\n\n- corresponds to the version of the ``zope.exceptions`` package shipped as part of\n  the zope 3.2.0 release.\n\n- deprecated the ``inotfounderror`` interface and the corresponding\n  ``notfounderror`` exception class, in favor of \"standard\" exceptions\n  ``attributeerror``, ``keyerror``).  the deprecated items will be removed in\n  zope 3.3.\n\n\n3.0.0 (2004-11-07)\n==================\n\n- corresponds to the version of the zope.exceptions package shipped as part of\n  the zope x3.0.0 release.\n",
  "docs_url": null,
  "keywords": "zope exceptions",
  "license": "zpl 2.1",
  "name": "zope.exceptions",
  "package_url": "https://pypi.org/project/zope.exceptions/",
  "project_url": "https://pypi.org/project/zope.exceptions/",
  "project_urls": {
    "Homepage": "https://github.com/zopefoundation/zope.exceptions",
    "Issue Tracker": "https://github.com/zopefoundation/zope.exceptions/issues",
    "Sources": "https://github.com/zopefoundation/zope.exceptions"
  },
  "release_url": "https://pypi.org/project/zope.exceptions/5.0.1/",
  "requires_dist": [
    "setuptools",
    "zope.interface",
    "Sphinx ; extra == 'docs'",
    "repoze.sphinx.autointerface ; extra == 'docs'",
    "zope.testrunner ; extra == 'test'"
  ],
  "requires_python": ">=3.7",
  "summary": "zope exceptions",
  "version": "5.0.1",
  "releases": [],
  "developers": [
    "zope-dev@zope.dev",
    "zope_foundation_and_contributors"
  ],
  "kwds": "zopeexceptions pyversions zope assert_ notfounderror",
  "license_kwds": "zpl 2.1",
  "libtype": "pypi",
  "id": "pypi_zope.exceptions",
  "homepage": "https://github.com/zopefoundation/zope.exceptions",
  "release_count": 28,
  "dependency_ids": [
    "pypi_repoze.sphinx.autointerface",
    "pypi_setuptools",
    "pypi_sphinx",
    "pypi_zope.interface",
    "pypi_zope.testrunner"
  ]
}